export const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
]

export const DISTRICTS = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Nellore', 'Visakhapatnam'],
  'Arunachal Pradesh': ['Itanagar', 'Tawang', 'West Kameng', 'Papum Pare'],
  Assam: ['Kamrup', 'Guwahati', 'Dibrugarh', 'Jorhat', 'Silchar', 'Nagaon'],
  Bihar: ['Patna', 'Gaya', 'Muzaffarpur', 'Bhagalpur', 'Darbhanga', 'Nalanda'],
  Chhattisgarh: ['Raipur', 'Bilaspur', 'Durg', 'Bastar', 'Raigarh'],
  Goa: ['North Goa', 'South Goa'],
  Gujarat: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Gandhinagar'],
  Haryana: ['Gurugram', 'Faridabad', 'Karnal', 'Hisar', 'Sirsa', 'Ambala', 'Panipat'],
  'Himachal Pradesh': ['Shimla', 'Kangra', 'Mandi', 'Solan', 'Kullu'],
  Jharkhand: ['Ranchi', 'Dhanbad', 'Jamshedpur', 'Hazaribagh', 'Bokaro'],
  Karnataka: ['Bengaluru Urban', 'Bengaluru Rural', 'Mysuru', 'Belagavi', 'Dharwad', 'Kalaburagi', 'Tumakuru'],
  Kerala: ['Thiruvananthapuram', 'Ernakulam', 'Kozhikode', 'Thrissur', 'Kottayam', 'Palakkad'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar'],
  Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Ahmednagar', 'Aurangabad', 'Solapur', 'Kolhapur'],
  Manipur: ['Imphal East', 'Imphal West', 'Thoubal', 'Churachandpur'],
  Meghalaya: ['East Khasi Hills', 'West Garo Hills', 'Ri Bhoi'],
  Mizoram: ['Aizawl', 'Lunglei', 'Champhai'],
  Nagaland: ['Kohima', 'Dimapur', 'Mokokchung'],
  Odisha: ['Khordha', 'Cuttack', 'Puri', 'Sambalpur', 'Balasore', 'Ganjam'],
  Punjab: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali'],
  Rajasthan: ['Jaipur', 'Jodhpur', 'Kota', 'Udaipur', 'Ajmer', 'Bikaner', 'Alwar'],
  Sikkim: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Thanjavur', 'Tiruchirappalli', 'Erode'],
  Telangana: ['Hyderabad', 'Rangareddy', 'Warangal', 'Karimnagar', 'Nizamabad', 'Khammam'],
  Tripura: ['West Tripura', 'South Tripura', 'North Tripura', 'Dhalai'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur Nagar', 'Varanasi', 'Agra', 'Meerut', 'Prayagraj', 'Ghaziabad', 'Bareilly'],
  Uttarakhand: ['Dehradun', 'Haridwar', 'Nainital', 'Udham Singh Nagar', 'Pauri Garhwal'],
  'West Bengal': ['Kolkata', 'Howrah', 'North 24 Parganas', 'Hooghly', 'Bardhaman', 'Murshidabad', 'Darjeeling'],
  'Andaman and Nicobar Islands': ['South Andaman', 'North and Middle Andaman', 'Nicobar'],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Dadra and Nagar Haveli'],
  Delhi: ['New Delhi', 'Central Delhi', 'South Delhi', 'North Delhi', 'East Delhi', 'West Delhi', 'Dwarka'],
  'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur'],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Kavaratti', 'Agatti', 'Minicoy'],
  Puducherry: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
}

export const CROPS = [
  'Wheat',
  'Paddy',
  'Maize',
  'Onion',
  'Potato',
  'Tomato',
  'Soyabean',
  'Mustard',
  'Cotton',
  'Turmeric',
  'Chilli',
  'Groundnut',
  'Bajra',
  'Jowar',
  'Sugarcane',
  'Pulses',
]
